#index:
#    path: /
#    controller: App\Controller\DefaultController::index

article_list:
    path: /articles
    controller: App\Controller\ArticleController::getArticles

articles:
    path: /articles
    controller: App\Controller\ArticleController::store